apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole-ingressroute
  namespace: pihole-namespace
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`pihole.inf.lan`)
      priority: 10
      middlewares:
        - name: redirect-root-to-admin
          namespace: pihole-namespace
      services:
        - name: pihole
          port: 8081
