apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole-namespace

resources:
  - namespace.yaml
  - pvcs.yaml
  - deployment.yaml
  - service.yaml
  - middleware.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: pihole
  app.kubernetes.io/component: dns-server

images:
  - name: pihole/pihole
    newTag: 2025.06.2
