apiVersion: apps/v1
kind: Deployment
metadata:
  name: newt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newt
  template:
    metadata:
      labels:
        app: newt
    spec:
      containers:
      - name: newt
        image: fosrl/newt:latest
        env:
        - name: PANGOLIN_ENDPOINT
          value: "https://pangolin.ricearaul.com"
        - name: NEWT_FIXED_SUBNETS
          value: "192.168.77.0/24"
        - name: NEWT_ID
          valueFrom:
            secretKeyRef:
              name: newt-credentials
              key: NEWT_ID
        - name: NEWT_SECRET
          valueFrom:
            secretKeyRef:
              name: newt-credentials
              key: NEWT_SECRET
