apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox-ingressroute
  namespace: proxmox-routing
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`proxmox.inf.lan`)
      services:
        - name: proxmox-service
          port: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-service
  namespace: proxmox-routing
spec:
  clusterIP: None
  ports:
    - port: 8006
      targetPort: 8006
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-service
  namespace: proxmox-routing
subsets:
  - addresses:
      - ip: 192.168.77.2
    ports:
      - port: 8006