apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox-ingressroute
  namespace: proxmox-routing
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`proxmox.inf.lan`)
      services:
        - name: proxmox-svc
          kind: TraefikService
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: proxmox-svc
  namespace: proxmox-routing
spec:
  weighted:
    services:
      - name: proxmox-backend
        port: 8006
        weight: 1
        scheme: https
        serversTransport: proxmox-transport
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: proxmox-transport
  namespace: proxmox-routing
spec:
  insecureSkipVerify: true  # Proxmox uses self-signed certificates
---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-backend
  namespace: proxmox-routing
spec:
  clusterIP: None
  ports:
    - port: 8006
      targetPort: 8006
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-backend
  namespace: proxmox-routing
subsets:
  - addresses:
      - ip: 192.168.77.2
    ports:
      - port: 8006