apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wg-easy-namespace

resources:
  - namespace.yaml
  - pvcs.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: wg-easy
  app.kubernetes.io/component: vpn-server

images:
  - name: ghcr.io/wg-easy/wg-easy
    newTag: "15"
