apiVersion: v1
kind: Service
metadata:
  name: wg-easy-lb
  namespace: wg-easy-namespace
spec:
  selector:
    app: wg-easy
  type: LoadBalancer
  loadBalancerIP: 192.168.77.170
  ports:
    - name: wg
      port: 51820
      targetPort: 51820
      protocol: UDP
    - name: http
      port: 51821
      targetPort: 51821
      protocol: TCP
